name: aleo_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  bip39: ^1.0.6
  crypto: ^3.0.3
  ffi: ^2.1.0

dev_dependencies:
  convert: ^3.1.1
  lints: ^2.0.0
  test: ^1.21.0
